repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v4.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: pretty-format-json
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: flake8
        name: Running flake8 from local poetry env
        entry: poetry run flake8 .
        language: python
        language_version: python3.9
        files: ".*.py"
-   repo: local
    hooks:
    -   id: isort
        name: Running isort from local poetry env
        entry: poetry run isort .
        language: python
        language_version: python3.9
        files: ".*.py"
